replicaCount: 1

name: {{ service_name }}

image:
  repository: ghcr.io/klub-inzenjera/{{ service_name }}
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 80
