replicaCount: 1

name: user-service-web

image:
  repository: ghcr.io/klub-inzenjera/user-service-web
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 80
