name: Initialize project
on:
  repository_dispatch:
    types: [init]

permissions:
  contents: write

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract repo name
        id: vars
        run: |
          echo "repo_name=${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT

      - name: Replace Helm placeholders
        run: |
          find helm -type f -name "values.yaml" -exec sed -i "s/{{ service_name }}/${{ steps.vars.outputs.repo_name }}/g" {} \;

      - name: Delete this workflow
        run: |
          rm .github/workflows/init.yml

      - name: Commit changes (replace + delete)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Initialize Helm values and remove init workflow"
          git push